"""Pick demo customers (each with an approved purchase and a declined payment in the 60-day window) and write the
mock IdP's LABELED TEST identities. Generated locally; the output file is gitignored."""
import json
from pathlib import Path

import duckdb
import yaml

from bankagent.identity.users import hash_password


def select_demo_customers(serving_dir: Path, per_country: dict[str, int]) -> list[dict]:
    serving_dir = Path(serving_dir)
    p = json.loads((serving_dir / "latest.json").read_text())
    run, as_of = serving_dir / p["run_id"], p["max_process_date"]
    cases = " ".join(f"when '{country}' then {n}" for country, n in per_country.items())
    sql = f"""
      with t as (select * from read_parquet('{run}/fct_transaction/*.parquet')
                 where process_date between DATE '{as_of}' - INTERVAL 60 DAY and DATE '{as_of}'),
      ok as (select customer_id from t group by customer_id
             having count(*) filter (where transaction_status = 'Approved' and transaction_type = 'Purchase'
                                     and merchant_name is not null) > 0
                and count(*) filter (where transaction_status = 'Declined') > 0),
      c as (select c.customer_id, c.country from read_parquet('{run}/dim_customer/*.parquet') c join ok using (customer_id)),
      ranked as (select *, row_number() over (partition by country order by customer_id) as rn from c)
      select customer_id, country from ranked where rn <= (case country {cases} else 0 end)
      order by country, customer_id"""
    return [{"customer_id": r[0], "country": r[1]} for r in duckdb.sql(sql).fetchall()]


def build_users(customers: list[dict], pt_every: int = 4) -> list[dict]:
    users = []
    for i, c in enumerate(customers, start=1):
        users.append({"username": f"demo{i:02d}", "password_sha256": hash_password(f"demo-{i:02d}"), "otp": "123456",
                      "customer_id": c["customer_id"], "lang": "pt" if i % pt_every == 0 else "es"})
    return users


def write_users(path: Path, users: list[dict]) -> None:
    header = ("# LABELED TEST identities for the mock identity service (generated by scripts/pick_demo_users.py).\n"
              "# Passwords are demo-NN, OTP 123456. Portuguese sessions are customers who chose PT: the dataset has\n"
              "# no Portuguese-speaking customers (spec §2).\n")
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(header + yaml.safe_dump({"users": users}, sort_keys=False, allow_unicode=True))
