"""Final model choice on the real-text dev set, temperature calibration, promotion into the package, and the model
card. Ties within 2 points of hard-slice top-1 go to logistic regression."""
import json
import shutil
from pathlib import Path

import numpy as np

from bankagent.resolver.features import FEATURES, case_features
from bankagent.resolver.model import ARTIFACT_DIR, Resolver, with_none
from bankagent.resolver.train import case_metrics

TIE_MARGIN = 0.02
T_BOUNDS = (0.05, 20.0)


def _groups(resolver: Resolver, rows: list[dict]) -> list[tuple[np.ndarray, int]]:
    """(logits, index of the right answer) per dev row; not_in_list rows point at the 'none' slot (index n)."""
    out = []
    for r in rows:
        ids = [t["transaction_id"] for t in r["candidates"]]
        logits = resolver.raw(case_features(r["extraction"]["mentions"], r["candidates"]))[0]
        out.append((logits, ids.index(r["target_id"]) if r["target_id"] is not None else len(ids)))
    return out


def fit_temperature(resolver: Resolver, rows: list[dict]) -> float:
    """Minimize the negative log-likelihood of the 'none of these' softmax on every dev row."""
    from scipy.optimize import minimize_scalar

    groups = _groups(resolver, rows)

    def nll(t: float) -> float:
        return -sum(float(np.log(with_none(logits, t)[i] + 1e-12)) for logits, i in groups)

    return float(minimize_scalar(nll, bounds=T_BOUNDS, method="bounded").x)


def choose_finalist(finalists: dict[str, dict], rows: list[dict]) -> tuple[str, dict[str, dict]]:
    metrics = {fam: case_metrics(Resolver.load(Path(f["path"])), rows, "extraction") for fam, f in finalists.items()}
    score = {fam: m["top1_hard"] or 0.0 for fam, m in metrics.items()}
    best = max(score, key=score.get)
    if "logreg" in score and score["logreg"] >= score[best] - TIE_MARGIN:
        best = "logreg"
    return best, metrics


def promote(src: Path, temperature: float, extra: dict, dst: Path = ARTIFACT_DIR) -> Resolver:
    spec = json.loads((src / "model.json").read_text(encoding="utf-8"))
    spec["temperature"] = temperature
    spec["metadata"] = spec["metadata"] | extra
    dst.mkdir(parents=True, exist_ok=True)
    if spec.get("model_file"):
        shutil.copy2(src / spec["model_file"], dst / spec["model_file"])
    (dst / "model.json").write_text(json.dumps(spec, indent=1), encoding="utf-8")
    return Resolver.load(dst)


def _fmt(v) -> str:
    return "n/a" if v is None else (f"{v:.3f}" if isinstance(v, float) else str(v))


def write_model_card(dst: Path, resolver: Resolver, family_metrics: dict[str, dict], dev_after: dict) -> Path:
    md = resolver.spec["metadata"]
    rows = "\n".join(f"| {fam} | {_fmt(m['top1'])} | {_fmt(m['top1_hard'])} | {_fmt(m['top1_easy'])} | "
                     f"{_fmt(m['nil_auc'])} | {_fmt(m['ece'])} |" for fam, m in family_metrics.items())
    text = f"""# Transaction resolver model card ({resolver.version})

Spec: `docs/design/2026-09-29-transaction-resolver-design.md`. Generated by `scripts/resolver.py finalize`.

## Model
- Family: **{md.get('family')}**, params `{json.dumps(md.get('params'))}`, temperature **{resolver.temperature:.3f}**.
- Features ({len(FEATURES)}): {', '.join(f'`{f}`' for f in FEATURES)}.
- Output: per-candidate probability and `p_none` from a softmax over [logits / T, 0] (the 0 is "none of these"),
  `best_raw_fit`, and the top-3 feature contributions per candidate.

## Intended use
Evidence for Jev's `target_transaction` decision in the LATAM Bank agent (Jev decides; code applies thresholds).
Not a fraud model, not an eligibility model, never acts alone in the agent.

## Data
- Training: {md.get('n_train')} simulated cases over real histories from serving run `{md.get('serving_run_id')}`,
  simulator `{md.get('simulate_version')}` (sha256 `{str(md.get('simulate_sha256'))[:12]}…`), seed {md.get('seed')}.
- Hyperparameters chosen on {md.get('n_val')} simulated validation cases from dev customers.
- Splits: customers by sha256 bucket (0–7 train, 8 dev, 9 test); anchors train 2023-09…2025-09, dev 2025-10…2026-01,
  test 2026-02…2026-06-17. No customer or anchor period is shared.
- Dev: {dev_after['n']} Claude-written ES/PT messages read by the real `extract` (`resolver/data/dev_v1.jsonl`).

## Dev results (real text; choice between family finalists)
| Family | top-1 | top-1 hard | top-1 easy | not_in_list AUC | ECE (T=1) |
|---|---|---|---|---|---|
{rows}

After calibration: ECE **{_fmt(dev_after['ece'])}** (top-1 and AUC do not depend on the temperature).

## Limitations
- Trained on simulated mentions; the style rates in `simulate.yaml` are assumptions. Dev and test are real text.
- Portuguese messages describe the histories of Spanish-speaking customers (the data has no Portuguese customers).
- Ignores wording, negation and conversation context by design; those are Jev's job.
- The test-set result lives in `resolver/reports/`, not here: this card only shows data used for model choices.
"""
    path = dst / "MODEL_CARD.md"
    path.write_text(text, encoding="utf-8")
    return path
